### ISSUE TITLE
Opening OPP3 from Zoho

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#1]
From Zoho Contact module, the user opens the OPP record

![image](https://user-images.githubusercontent.com/19645356/40650850-85a4bd82-6334-11e8-836a-484fc91a1d9b.png)

**Comment by AntoineSelectra** [comment]
To be verified: the Contact ID is put in "Contact Id" (and not Lead Id as it was the case until now)

**Comment by Finkels** [comment]
the url invoke by the botton of opp : https://italia2.opp.selectra.io?lead_source=${Contacts.Lead Source}&leadid=${Contacts.Contact Id}&owner=${Contacts.Contact Owner}&phone=${Contacts.Phone}&firstname=${Users.First Name}&lastname=${Users.Last Name}&email=${Users.Email}&interaction=${Unsupported_Field}

**Comment by AntoineSelectra** [comment]
- [ ] The "OPP 2 Italia" button set up by Joseph does not open a new record page
![image](https://user-images.githubusercontent.com/19645356/40654799-9a55239c-633f-11e8-9f87-9ebd6925ed14.png)

**Comment by AndrewTi** [comment]
I think the request has to look like this: http://italia2.opp.selectra.io/#!/import/zoho?

**Comment by Finkels** [comment]
i made the change with the url that @AndrewTi provide me

**Comment by AntoineSelectra** [comment]
@AndrewTi , you can fix the bug now. I have changed the url linking Zoho to the OPP, the new url is more simple:
http://italia2.opp.selectra.io/#!/import/zoho?lead_source=${Contacts.Lead Source}&leadid=${Contacts.Contact Id}&owner=${Contacts.Contact Owner}&phone=${Contacts.Phone}&lastname=${Contacts.Last Name}

example:
http://italia2.opp.selectra.io/#!/import/zoho?lead_source=it-ei-cc-confronto&leadid=1499247000292249043&owner=Sara%20Sozzo&phone=393478961727&lastname=393478961727

Result: it does not work
- [ ] Contact Owner and Cognome/Ragione Sociale are not imported
- [ ] the page goes in a loop
![image](https://user-images.githubusercontent.com/19645356/40676965-9302c3fa-637c-11e8-9c8c-5e0d575b2dfb.png)

**Comment by AndrewTi** [comment]
fixed

**Comment by AntoineSelectra** [comment]
"Open Contract id in Zoho" --> "Open Contact in Zoho"

**Comment by AndrewTi** [comment]
fixed
