### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#10]
Strange case - with record 11640 ARELTEST3105

If I try to download clicking on DOUBLE, it says "pdf-template has been not found"

If I try to download clicking on LUCE, it says "Whoops, looks like something went wrong."
![image](https://user-images.githubusercontent.com/19645356/40788545-a00fe206-64f0-11e8-9bf1-7bdfe6a231e0.png)

What do these errors mean @AndrewTi ?

**Comment by AndrewTi** [comment]
problem in REMI 
the script tried to take remi_manual but the field does not exist so in result we have the error

**Comment by AntoineSelectra** [comment]
Can we shortcut this error? Or put a rule that says

`IF remi_manual is empty THEN remi_manual is nd` ?

**Comment by AndrewTi** [comment]
done

**Comment by AntoineSelectra** [comment]
Very strange, the bug is solved on some records but on some other it is still here.

Example: http://italia2.opp.selectra.io/#!/records/11646

**Comment by AndrewTi** [comment]
I don't see the issue on the record

**Comment by AndrewTi** [comment]
fixed

**Comment by AntoineSelectra** [comment]
New strange issue, I was making a test with a new record created from scratch in Zoho and downloading the contract, instead of the correct name, it was called: _lead-it-DUAL-leadsource_
I have tried to recreate the bug but now the system seems to work properly
![image](https://user-images.githubusercontent.com/19645356/40873163-a2acd796-665b-11e8-94a5-a737440b3b52.png)

**Comment by AndrewTi** [comment]
fixed

**Comment by AntoineSelectra** [comment]
I can't download the pdf template for this record
http://italia2.opp.selectra.io/#!/records/11649
operation is **IR Subentro EE** and it works with another record
http://italia2.opp.selectra.io/#!/records/11648

Error is: http://italia2.opp.selectra.io/api/v1/records/11649/pdf?type=luce
![image](https://user-images.githubusercontent.com/19645356/40879252-946d5f60-669d-11e8-86a0-ca42b8e6f1c1.png)

**Comment by AndrewTi** [comment]
fixed
