### ISSUE TITLE
IBAN section

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#16]
- [x] SET SAME AS ABOVE button does not work. Cognome, Nome and Codice fiscale from Intestatario info should be copied
- [x] typos in the button:
_HOME --> NOME_
_FISCASE --> FISCALE_

![image](https://user-images.githubusercontent.com/19645356/40873070-dc925ece-6659-11e8-8e02-4783dbabcd67.png)

**Comment by AndrewTi** [comment]
fixed
