### ISSUE TITLE
New fields for "land registers"

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#21]
For some operations, our customers are asked to provide very detailed data about their house (how and when it was recorded in official land registers).

Therefore, we would need the following new fields, in a new section called "Dati catastali"
- SCALA
- PIANO
- INTERNO
- SEZIONE CATASTO
- FOGLIO
- PARTICELLA
- SUB
--> all these fields are VARCHAR(5) (small field, max 5 characters, so you could put 3 or 4 per lines)

- ATTO
Select field,with the following options (6): ATTO NOTARILE, SCRITTURA PRIVATA, PROVVEDIMENTO GIUDIZIARIO, DONAZIONE, TESTAMENTO, ALTRO (SPECIFICARE)

- DATA ATTO  (date field)
- LUOGO REGISTRAZIONE (varchar)
- DATA REGISTRAZIONE  (date field)
- NUMERO ATTO (varchar)

Where?
The section "Dati catastali" goes right after "Punto di prelievo", with a button "Hide/Show" (default: the section is hidden)
![image](https://user-images.githubusercontent.com/19645356/41094344-46da4132-6a4e-11e8-9cd7-6a1c0a609d22.png)

**Comment by AntoineSelectra** [comment]
Good, one thing: change date format to dd/mm/yyyy

for PDF and Zoho
    [DATA_ATTO] => 2005-06-15T22:00:00.000Z
    [DATA REGISTRAZIONE] => 2005-06-16T22:00:00.000Z

**Comment by AndrewTi** [comment]
done
