### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#23]
- [x] In Section "FATTURAZIONE E MODALITà DI RICEZIONE DEL CONTRATTO"
IF [FATTURA SPEDIZIONE] is "Solo e-Mail" OR  "e-Mail+cartacea" THEN [EMAIL DI FATTURAZIONE] is mandatory
![image](https://user-images.githubusercontent.com/19645356/41502268-d9a30c32-71b6-11e8-84ef-3c2d715705c4.png)

- [x] IF [Product GAS] is filled/not null THEN [REMI] field is mandatory

- [x] in "Punto di prelievo" section, with the Google API, make "Civico" not mandatory so it can work with an incomplete address like _Via Nazionale, Roma RM, Italy_
![image](https://user-images.githubusercontent.com/19645356/41502399-a2f9544a-71b9-11e8-9bb9-66eb26828a8c.png)

**Comment by AndrewTi** [comment]
1: process
2: done
3: done

**Comment by AntoineSelectra** [comment]
Great!
