### ISSUE TITLE
Data entry - Product fields

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#26]
When these fields are completed, when they are cancelled, the previous value remains
http://italia2.opp.selectra.io/#!/records/11960
![image](https://user-images.githubusercontent.com/19645356/41557283-68f2325a-733d-11e8-815f-1cc99e7292f2.png)

For instance I have tried to cancel the Product Gas, but it's still shown. This bug is present for both Power and Gas

**Comment by AndrewTi** [comment]
done
