### ISSUE TITLE
Data entry - small typos / formating

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#4]
- [x] ADD: “Inizio data fornitura” for both POWER and GAS (“Luce” and “Gas” sections)
![image](https://user-images.githubusercontent.com/19645356/40651761-c9da7224-6336-11e8-881e-87ef6405148e.png)
- [x] invert the position of 2 fields
![image](https://user-images.githubusercontent.com/19645356/40656679-72c15fc0-6345-11e8-9017-82f4af6abea3.png)

**Comment by AndrewTi** [comment]
1: fixed
2: fixed
