### ISSUE TITLE
Scripts/Operation-template management

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#5]
- [ ] Add date of last update
![image](https://user-images.githubusercontent.com/19645356/40652510-ae2d9e28-6338-11e8-9c65-4d154a616e8d.png)

**Comment by AndrewTi** [comment]
fixed

**Comment by AntoineSelectra** [comment]
Thanks, can we change all date to european standard? dd/mm/yyy ?

**Comment by AndrewTi** [comment]
done

**Comment by AntoineSelectra** [comment]
Seen, is it possible to have the month always with 2 figures? 

30/5/18 8:23 PM -->  30/05/18 8:23 PM

**Comment by AndrewTi** [comment]
yes

**Comment by AndrewTi** [comment]
done

**Comment by AntoineSelectra** [comment]
All good, except for PDF TEMPLATES
![image](https://user-images.githubusercontent.com/19645356/40846834-fff0b982-65ba-11e8-86ce-7b869b357ebe.png)

**Comment by AndrewTi** [comment]
done
