### ISSUE TITLE
Data entry form - small bugs / UX

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#6]
**Secondary addresses (residenza, iban, fatturazione)**
- [x] when selecting "SET AS SAME AS PUNTO DI PRELIEVO" or "SET SAME AS RESIDENZA", nothing happens. Could it be possible to "highlight" the selected option? Or write down under the buttons:
_Address selected: [the address selected]_
![image](https://user-images.githubusercontent.com/19645356/40655566-01ebcd6a-6342-11e8-9249-28f159d3d6fb.png)
- [x] IBAN CAP gives a message of error
![image](https://user-images.githubusercontent.com/19645356/40655970-32f8eed2-6343-11e8-963a-6cbb1861dfc9.png)
- [x] Lead Source is not saved, for instance italia2.opp.selectra.io/#!/records/11637 was filled with _it-ei-cc-confronto_ and saved but when reopened, the Lead Source field is empty

**Gas section**
- [x] Periodicità della fatturazione GAS can't be filled, it's impossible to write
![image](https://user-images.githubusercontent.com/19645356/40656772-c0bc9186-6345-11e8-8a9c-42fef622420d.png)

**Comment by AndrewTi** [comment]
2: we are checking the CAP in our DB so if the CAP doesn't exist we will have the error

3: fixed

**Comment by AntoineSelectra** [comment]
2: so basically we don't have any CAP in our DB for now, is that right?

**Comment by AndrewTi** [comment]
1: done
