### ISSUE TITLE
PDF contract download

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#7]
- [x] the name of the file is always DUAL, we cannot choose EE or GAS
- [ ] remove "-" between name and surname
Contratto-DUAL-NOME2905-TESTFULL2905.pdf  --> Contratto-DUAL-NOME2905 TESTFULL2905.pdf

**Comment by AndrewTi** [comment]
1: always DUAL because you have only operation template selected
for EE and GAS, you need to select operation in the fields:
- operation LUCE in LUCE section
- operation GAS in GAS section

**Comment by AndrewTi** [comment]
fixed
