### ISSUE TITLE
Syncing with Zoho

### ISSUE THREAD

**Issue by AntoineSelectra** [AntoineSelectra/OPP3#8]
- [x] Syncing does not work for records/11637 (almost fully completed) - do you why @AndrewTi ?
- [x] with records/11638 (only name and fiscal code filled), sync seems to work but when trying to open the Contact in Zoho, it does not work
--> it opens a Lead https://crm.zoho.com/crm/tab/Leads/1499247000293468109/
--> it says the Record is not available (probably because it tries to open a Lead with a Contact ID number)

**Comment by AndrewTi** [comment]
1: done
